# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  base = "./"
  publish = "public/"
  command = "yarn build"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
